### ISSUE TITLE
Problema com input type submit

### ISSUE THREAD

**Issue by micheltlutz** [PhilippeAssis/custom-alert#3]
Estou usando faces e preciso colocar a confirmation em um input type submit o problema é que este meu input tem um evento onclick onde tenho este exemplo

<input type="submit" onclick="return confirm('Isso é um exemplo?'),function (data) {
            if (data)
                return true;
            else
                return false;
        }, {return: true};" value="Confirmar3">

Mas não consigo ter o return do confirm o submit ocorre antes de escolher a opção.

**Comment by codephi** [comment]
O confirm é um void, a unica maneira de tratar o resultado dele é por um callback. Acabei de atualizar para a versão 2.0 dá uma olhada na documentação. Se tiver duvida me chama aqui mesmo. Não vou fechar agora,
