### ISSUE TITLE
Not take account focus on cancel button

### ISSUE THREAD

**Issue by Rizzen59** [PhilippeAssis/custom-alert#4]
Hello,

I have a case that cancel button have to be the default button selected in case of press on enter button.

I would like to create Pullrequest so as to send my solution but i can't.

I modified js to add this block code for keynum == 13

```
if (document.getElementById("customconfirm").style.display == "block"){
	var focusButton = document.activeElement;
	if(focusButton !== null && focusButton.classList.contains("button-cancel")){
		window.customconfirm.cancel();
	} else {						
		window.customconfirm.done();
	}
}
```

**Comment by codephi** [comment]
Good.
I'll add here.
But why can not you send a Pull Request?

**Comment by Rizzen59** [comment]
I tried it, but i dont know why my job's PC doesn't want to clone github repo. Directly from git or with github client. I have to search solution but not enougth time for the moment.

**Comment by codephi** [comment]
Okay. Create your suggestion. Notice the structure of the changed options object. The update is available in the [readme ](https://github.com/PhilippeAssis/custom-alert#keyboard-events) and the demo page.
