### ISSUE TITLE
Blocks all text input from the keyboard (e.g. to an HTML input field)

### ISSUE THREAD

**Issue by ajck** [PhilippeAssis/custom-alert#7]
After using custom alert in my web app and finding that all text input from the keyboard was blocked, I downloaded the zip archive of all the files from this repo, and in the demo page added in a simple html form with a text input after the body tag in the index.html of the demo page, so it looks like:

```
<body>
<form>
<input type="text">
</form>
...
```
etc...
After you've clicked through the demo alerts, you can click in the form field to activate it, but all keyboard input is ignored - nothing comes up...

Custom-alert is great, thanks for making it, just needs couple of problems fixed :)

**Comment by codephi** [comment]
Are you using IE? This lib does not support IE. But you can suggest this correction if you feel at ease.

**Comment by codephi** [comment]
Try to use the new master merge, please #5 @ajck
